
FROM ubuntu:18.04

RUN apt update; \
    apt-get install -y apt-transport-https wget gnupg2; \
    wget -qO - https://apt.signalsciences.net/release/gpgkey | apt-key add -; \
    echo "deb https://apt.signalsciences.net/release/ubuntu/ bionic main" | tee /etc/apt/sources.list.d/sigsci-release.list; \
    apt-get update

CMD ["/usr/sbin/sigsci-agent"]
